# Aprendiendo y Practicanto Numpy con Ejemplo y Ejericios

A continuacion veremos algunos ejempos de funciones las cuales nos podrian llegar a ser muy utiles al momento de trabajar con Numpy esto junto a una parte de elaboracion de ejercicios los cuales nos ayudaran a entender y visualizar el funcionamiento de esas herramientas en problemas reales.

Lo primero que debemos hacer es importar las librerias que vamos a utilizar, las cuales serian Numpy y Matplotlib, esta ultima nos ayudara con los graficos de los datos.

In [7]:
import numpy as np # ponemos np como alias de numpy y poderlo llamar mas facil   
import matplotlib.pyplot as plt

## Lo primero que veremos sera el **Basic Indexer**
el cual nos permite visualizar en consola un elemento en especifico en un arreglo.

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) 

30


Como logramos observar el resultafo fue 30, ya que el indice 2 corresponde al tercer elemento de la lista, teniendo en cuenta de que las posiciones comienzan desdel el 0.

## Lo siguente que veremos sera el **Slicing**
el cual nos ayudara a visualizar solamente un intervalo de elementos de un arreglo

In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) 

[20 30 40]


Como pudimos ver, pudimos ver como acceder a un conjunto de elementos o a un rango de elementos de un array.

## Ahora veremos los **Indexings en arreglos en 2D**.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2]) 

6


Lo que nos quiere decir el 2D array es que en una matriz nxm podemos dar una instruccion de impresion en consola del elemento que se encuentra en la posicion 1 (filas), 2 (columnas).

## Lo siguiente que veremos sera el **Slicing en un 2D array**.

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2, 1:]) # Output: [[2 3] [5 6]]

[[2 3]
 [5 6]]


Aqui los que nos muestra es que nos mostrará todas las filas desde el inicio hasta la fila en posicion 2 y todas las columnas desde la columna 1 hasta el final.


## Ahora lo veremos los **Indexing pero en Tensores 3D**

In [12]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]],
[[13, 14, 15], [16, 17, 18]]])

# Access specific elements
print(tensor[1, 0, 2])

# Access an entire "slice" (2D submatrix)
print(tensor[1]) 

9
[[ 7  8  9]
 [10 11 12]]


Un tensor 3D en NumPy es básicamente un arreglo con 3 dimensiones. Puedes pensarlo como una lista de matrices (o una "caja" que contiene varias matrices 2D apiladas una encima de la otra).

Por ejemplo, el tensor 3D que utilizamos en el codigo de arriba, se refiere a una especie de una matriz con 3 sub matrices de 2x3 cada una.

La sintaxis para acceder al tensor es la siguiente:
tensor[depth, row, col]

Asi que segun lo atenrior el output que nos solto la consola anteriormente se refiere a:
tensor[1, 0, 2] → segunda matriz, primera fila, tercera columna (uotput: 9)

Como tambien podemos hacer que nos imprima todo el tensor que se encuentra en una posicion especifica.
Tensor[1] → toda la matriz 2x3 ubicada en la posicion 1 de todo el arreglo (output: [[ 7  8  9]
 [10 11 12]])

## Ahora veremos un **Slicing en Tensor 3D** (corte por secciones)

In [16]:
tensor = np.arange(27).reshape(3, 3, 3)
# Slice along the first dimension
print(tensor[1]) # Output: 3x3 submatrix
# Slice along the second dimension
print(tensor[:, 1, :]) # Output: 3x3 submatrix
# Slice along the third dimension
print(tensor[:, :, 2]) # Output: 3x3 submatrix

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


En el código anterior, se crea un tensor con np.arange(27).reshape(3, 3, 3), es decir, 3 matrices de 3x3 con valores del 0 al 26.

Cuando usamos tensor[1], accedemos a la segunda matriz completa del tensor (una submatriz 3x3). En cambio, tensor[:, 1, :] toma la segunda fila (índice 1) de todas las matrices, y las organiza en una nueva matriz 3x3. Por último, tensor[:, :, 2] selecciona la tercera columna de todas las matrices, también devolviendo una matriz 3x3.

Este tipo de slicing nos permite extraer secciones específicas del tensor de forma rápida y eficiente.



## 4D Tensor Indexing:

In [17]:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Access specific elements
print(tensor[1, 2, 0, 3]) # Output: 47
# Access a whole "block" (3D sub-tensor)
print(tensor[1, 2]) # Output: 2x4x3 sub-tensor

43
[[40 41 42 43]
 [44 45 46 47]]


Un tensor 4D en NumPy es un arreglo con cuatro dimensiones, que puedes imaginar como una colección de bloques 3D organizados en un eje extra. En el código anterior, se crea un tensor con np.arange(48).reshape(2, 3, 2, 4), lo que genera 2 bloques, cada uno con 3 matrices de 2x4, usando los números del 0 al 47.

Cuando usamos tensor[1, 2, 0, 3], accedemos a un único elemento del tensor: el que está en el segundo bloque, tercera matriz, primera fila y cuarta columna. El valor obtenido en ese punto es 47.

En cambio, con tensor[1, 2] accedemos a una subestructura completa dentro del tensor: una matriz de tamaño 2x4 que representa todas las filas y columnas de la tercera matriz del segundo bloque.

Este tipo de indexado permite trabajar con estructuras complejas como secuencias de imágenes, datos volumétricos o entradas para redes neuronales, de forma clara y ordenada.